### ISSUE TITLE
{"error": "ERROR__GAME_LOGIN_FAILED"}

### ISSUE THREAD

**Issue by RadioactivePeaches** [haipro287/LOLAutoBargain#1]
![Screenshot 2021-08-03 192421](https://user-images.githubusercontent.com/69229439/128015050-5be75224-ede3-4139-aa18-f449cc8220a5.png)

**Comment by RadioactivePeaches** [comment]
TH server

**Comment by 0x5ea000000** [comment]
![image](https://user-images.githubusercontent.com/17197951/128021964-5090717a-5cb4-45b0-a994-9fe11a65e7e3.png)
mình vẫn dùng bình thường ạ, bạn thử mở lại game sau đó chạy lại tool  xem ạ. nhớ phải mở client trong lúc chạy đê tránh token hết hạn

**Comment by RadioactivePeaches** [comment]
Tôi đã thử chạy với tư cách quản trị viên, khởi động lại trò chơi. Nó vẫn không hoạt động. Nó có liên quan đến máy chủ Thái Lan không? (Tôi đang sử dụng google dịch xin lỗi)

**Comment by 0x5ea000000** [comment]
oh u can use English if okay haha. There is the same birthday event in Thailand server now? my tool wont work on Thailand server because of the server which the tool sends request to is Vietnam server. Thank for using my tool and how did you know my tool? XD

**Comment by 0x5ea000000** [comment]
just created thailand version, i dont know if it can work or not, try it yourself

**Comment by RadioactivePeaches** [comment]
I just did a quick search xD Yours is the easiest to use and the design is clean. Same event in Thailand.
![Screenshot 2021-08-03 211740](https://user-images.githubusercontent.com/69229439/128031556-fb93e198-894d-4f44-b7fa-bd451cf84ab1.png)

**Comment by RadioactivePeaches** [comment]
Works, thank you! How did you scrape the codes?

**Comment by 0x5ea000000** [comment]
get from LOL Vietnam fanpage and t think that both server have the same code format XD

**Comment by RadioactivePeaches** [comment]
How did you do it? There is Garena page with codes and discord server too so I can try to di it myself

**Comment by 0x5ea000000** [comment]
i didnt crawl the code, another Vietnamese dev did XD But i think you can try some fb comment crawlers and fetching them with the code format.
